// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Error": {
        "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
        "title": "Something went wrong!"
    },
    "IndexPage": {
        "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
        "title": "next-intl example",
        "text": "We are a full-cycle production company, ready to bring your boldest ideas to life.",
        "button": "Watch the showreel"
    },
    "LocaleLayout": {
        "title": "next-intl example"
    },
    "Navigation": {
        "projects": "Projects",
        "about": "About us",
        "contacts": "Contacts",
        "locale": "RU"
    }
};
export default messages;