// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Error": {
        "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
        "title": "Something went wrong!"
    },
    "LocaleLayout": {
        "title": "NEXTERA production"
    },
    "IndexPage": {
        "description": "Мы — продакшн полного цикла, готовый воплотить в жизнь самые смелые идеи",
        "title": "Главная | NEXTERA production",
        "text": "Мы — продакшн полного цикла, готовый воплотить в жизнь самые смелые идеи",
        "button": "Cмотреть шоурил"
    },
    "LocaleSwitcher": {
        "label": "Change language",
        "locale": "{locale, select, de {🇩🇪 Deutsch} en {🇺🇸 English} other {Unknown}}"
    },
    "Navigation": {
        "projects": "Проекты",
        "about": "О нас",
        "contacts": "Контакты",
        "locale": "ENG"
    },
    "NotFoundPage": {
        "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
        "title": "Page not found"
    }
};
export default messages;